clone_depth: 10

environment:

  matrix:
     #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
     #  VSVER: Visual Studio 14 2015 Win64
     #  Architecture: x86_amd64
     #  VCPREFIX:'C:\Program Files (x86)\Microsoft Visual Studio 14.0'
     #  VCVARS: 'VC\vcvarsall.bat'
     - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
       VSVER: Visual Studio 15 2017 Win64
       VCPREFIX: 'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community'
       VCVARS: 'VC/Auxiliary/Build/vcvars64.bat'

configuration: Release

os: Visual Studio 2015

install:
  - ps: $env:VCVARSALL = "`"$env:VCPREFIX/$env:VCVARS`" $Architecture"
  - call %VCVARSALL%
  - vcpkg install armadillo:x64-windows
  - vcpkg integrate install

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git clone https://github.com/Dyn4cast/Dyn4cast.git --depth 1
  - cd Dyn4cast
  - mkdir build && cd build
  - >
    cmake -G "%VSVER%"
    -DDEBUG=OFF -DPROFILE=OFF
    -DUSE_OPENMP=OFF
    -DBUILD_CLI_EXECUTABLES=OFF
    -DBUILD_JULIA_BINDINGS=OFF
    -DBUILD_PYTHON_BINDINGS=OFF
    -DBUILD_TESTS=OFF
    -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - >
    cmake --build . --
    /verbosity:minimal /nologo /p:Configuration=Release;Platform=x64
  - cd %APPVEYOR_BUILD_FOLDER% && mkdir build && cd build
  - ps: $env:Dyn4cast_LIB = "Dyn4cast/build/Release/Dyn4cast.lib"
  - ps: $env:Dyn4cast_INCLUDE = "Dyn4cast/build/include"
  - ps: $env:Dyn4cast_LIB = "$env:APPVEYOR_BUILD_FOLDER/$env:Dyn4cast_LIB"
  - ps: $env:Dyn4cast_INCLUDE = "$env:APPVEYOR_BUILD_FOLDER/$env:Dyn4cast_INCLUDE"
# TODO: use AppVeyor to build examples from Makefiles (or similar)
#  - >
#    cmake -G "%VSVER%"
#    -DDEBUG=OFF -DPROFILE=OFF
#    -DDyn4cast_LIBRARY:FILEPATH=%Dyn4cast_LIB%
#    -DDyn4cast_INCLUDE_DIR:PATH=%Dyn4cast_INCLUDE%
#    -DBUILD_PYTHON_BINDINGS=OFF -DCMAKE_BUILD_TYPE=Release
#    -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
#  - >
#    cmake --build . --
#    /verbosity:minimal /nologo /p:Configuration=Release;Platform=x64

artifacts:
#  - path: '**\*.zip'

notifications:
- provider: Email
  to:
  - job.nmadu@gmail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true

cache:
  - c:\tools\vcpkg\installed\
