comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
<<<<<<< HEAD
        informational: true

=======
        informational: true  

codecov:
  token: 6976a9e3-ad8a-4a65-8fb1-e35e0e04e152
>>>>>>> 784b6865cce8ea2b0ef5af2c753998906ca11cec
