on:
  workflow_call:
  secrets:
  codecov_token:
  required: true
workflow_dispatch:

  jobs:
  build_and_test:
  runs-on: ubuntu-latest
...
- name: Upload coverage reports to Codecov
uses: codecov/codecov-action@v4
with:
  token: ${{ secrets.codecov_token }}
verbose: true
